### ISSUE TITLE
Unity Windows Editor DllNotFoundException: flex-ui 

### ISSUE THREAD

**Issue by sdkl** [gilzoide/unity-flex-ui#2]
I very interest with this project,but as i try to add package in my project,i get this error
```
DllNotFoundException: flex-ui assembly:<unknown assembly> type:<unknown type> member:(null)
Gilzoide.FlexUi.Yoga.YGNode.Instantiate () (at Assets/ThirdLibrary/FlexUI/Runtime/Yoga/YGNode.cs:14)
Gilzoide.FlexUi.FlexLayout.get_LayoutNode () (at Assets/ThirdLibrary/FlexUI/Runtime/FlexLayout.cs:417)
Gilzoide.FlexUi.FlexLayout.UpdateNodeStyle () (at Assets/ThirdLibrary/FlexUI/Runtime/FlexLayout.cs:527)
Gilzoide.FlexUi.FlexLayout.OnValidate () (at Assets/ThirdLibrary/FlexUI/Runtime/FlexLayout.cs:678)
```
and when i set windows/x86_64/flex-ui.dll "load on startup" and restart unity,it took another error
```
Plugins: Failed to load 'Assets/ThirdLibrary/FlexUI/Plugins/windows/x86_64/flex-ui.dll' with error '%1 不是有效的 Win32 应用程序。
'.
```

Unity Version 2021.3.15f1
Windows Version win10 19045.3693

**Comment by gilzoide** [comment]
Hey @sdkl, I fixed Windows support, please try the `1.0.0-preview6` version.
Weird that the MinGW build I had made in Linux worked here, but the last one I made on macOS did not 🤷‍
Either way, since I was already in Windows, I just rebuilt the DLL with G++ in Windows and now it works, hurray!

**Comment by sdkl** [comment]
@gilzoide I try in my Windows, but the problem seems still exist.
And i build win dll via cmake and vs work well.
When i check the dll dependents, i found difference
![image](https://github.com/gilzoide/unity-flex-ui/assets/7053755/20c5e259-a640-4cf5-b767-f051df0b33cc)

**Comment by gilzoide** [comment]
Oooh, ok, that makes sense. Sorry about that, I forgot about that kind of problem with installed DLLs.
Thank you very much for finding the culprit, it should be easy enough to fix this.

**Comment by gilzoide** [comment]
So, @sdkl I was able to generate a DLL that depends solely on KERNEL32.dll and msvcrt.dll, both of which should be present by default in any Windows system. My MSVC setup is not working well, so I just linked libgcc and libstdc++ statically using MinGW. The library is now 1.4MB instead of ~200KB, but this shouldn't be much of a problem.

If you could please test the version in branch [bugfix/windows-dll-dependencies](https://github.com/gilzoide/unity-flex-ui/tree/bugfix/windows-dll-dependencies) and tell me if it works now, both in editor and player builds, I'd appreciate the feedback ^^

**Comment by dandevs** [comment]
Seems like this issue resurfaced in 1.0.3, downgrading to 1.0.2 fixed it.

**Comment by gilzoide** [comment]
Oh my, that's weird. Thanks for the report again!
In these cases, you can reopen the issue =]

**Comment by gilzoide** [comment]
Hey @dandevs, can you please check if branch `dockerfile-builders` works in your Windows?
I've added Dockerfiles for building the libraries. Both 1.0.2, 1.0.3 and this new branch work on my Windows machine, but I don't trust it for this kinds of problems. If you confirm it works, I'll merge it, consider this issue as fixed and release the new fixed version as 1.0.4.

**Comment by dandevs** [comment]
@gilzoide It works! Thanks =]

**Comment by gilzoide** [comment]
Nice! I'll always build for Windows using the Dockerfile to avoid problems. Version 1.0.4 is released, should be available in OpenUPM soon. Cheers \o/
