### ISSUE TITLE
Dynamic TMP_Text width

### ISSUE THREAD

**Issue by Michele-Santoni** [gilzoide/unity-flex-ui#41]
I tried to test the FlexLayout component when the length of the text of the TMP_Text can change.
The hierarchy is this:
- Root
- - Text_1_Parent
- - - Text_1
- - Text_2_Parent
- - - Text_2

Every gameobject has a FlexLayout component attached and they are set like this:

[ Root ]
![Image](https://github.com/user-attachments/assets/a570ee87-f00f-42f3-ad12-014dbcd7d1f1)

[ both Text_*_Parent gameobjects ]
![Image](https://github.com/user-attachments/assets/a96089c7-28dc-40ce-9042-54bcbaf29f56)

[ both Text gameobjects ]
![Image](https://github.com/user-attachments/assets/bf07b657-8cca-410d-bf93-a0b6ab3880fa)

As shown in the "Scroll View" smaple scene, I attached the ContextSizeFitter component (with the "Horizontal Fit" option set to "Preferred Size") to both the TMP_Text gameobjects and the result is this:
![Image](https://github.com/user-attachments/assets/8c5742fb-4af5-4ed5-93d9-579b98e6fe3e)
p.s. the red box is the Root gameobject and the white boxes are the Text_*_Parent gameobjects.

When I'm trying to get this result instead:
![Image](https://github.com/user-attachments/assets/df88a879-e7c8-4d02-827b-e1b5fc95b9c7)

Am I missing something? Do I need to change the settings of my FlexLayout in a certain way?

**Comment by gilzoide** [comment]
Hey @Michele-Santoni, thanks for the question.

The Root is your actual root FlexLayout, correct? So right now, the root FlexLayout size is fixed, its size is [used as the "available width/height"](https://github.com/gilzoide/unity-flex-ui/blob/30ea7a5980e4b111ed4462807adf9dfb6d091f41/Runtime/FlexLayout.cs#L552-L556) that Yoga library expects. So the root object won't resize because of its chindren's contents, even with "width = auto". Maybe we should make it clearer in the Inspector of the root that width/height doesn't affect the object itself 🤔

What you'll need to do is have the root layout occupy the whole space that should be available horizontally, even if the contents won't need all of it. The children text parents and the texts configs look fine, they should resize themselves based on the text contents, since their "width = auto".

By the way @lgarczyn, right now FlexLayout does not affect any children without FlexLayouts, so in this case the texts also need them. There are plans to have an alternative to FlexLayout that is actually a LayoutGroup and considers/affects direct children without FlexLayout components, but it hasn't been done yet (#27).

**Comment by lgarczyn** [comment]
> Hey @Michele-Santoni, thanks for the question.
> 
> The Root is your actual root FlexLayout, correct? So right now, the root FlexLayout size is fixed, its size is [used as the "available width/height"](https://github.com/gilzoide/unity-flex-ui/blob/30ea7a5980e4b111ed4462807adf9dfb6d091f41/Runtime/FlexLayout.cs#L552-L556) that Yoga library expects. So the root object won't resize because of its chindren's contents, even with "width = auto". Maybe we should make it clearer in the Inspector of the root that width/height doesn't affect the root layout itself 🤔
> 
> What you'll need to do is have the root layout occupy the whole space that should be available horizontally, even if the contents won't need all of it. The children text parents and the texts configs look fine, they should resize themselves based on the text contents, since their "width = auto".
> 
> By the way @lgarczyn, right now FlexLayout does not affect any children without FlexLayouts, so in this case the texts also need them. There are plans to have an alternative to FlexLayout that is actually a LayoutGroup and considers/affects direct children without FlexLayout components, but it hasn't been done yet (#27).

Damn, i saw the closed issue and I thought that was handled

**Comment by Michele-Santoni** [comment]
> Hey [@Michele-Santoni](https://github.com/Michele-Santoni), thanks for the question.
> 
> The Root is your actual root FlexLayout, correct? So right now, the root FlexLayout size is fixed, its size is [used as the "available width/height"](https://github.com/gilzoide/unity-flex-ui/blob/30ea7a5980e4b111ed4462807adf9dfb6d091f41/Runtime/FlexLayout.cs#L552-L556) that Yoga library expects. So the root object won't resize because of its chindren's contents, even with "width = auto". Maybe we should make it clearer in the Inspector of the root that width/height doesn't affect the root layout itself 🤔
> 
> What you'll need to do is have the root layout occupy the whole space that should be available horizontally, even if the contents won't need all of it. The children text parents and the texts configs look fine, they should resize themselves based on the text contents, since their "width = auto".
> 
> By the way [@lgarczyn](https://github.com/lgarczyn), right now FlexLayout does not affect any children without FlexLayouts, so in this case the texts also need them. There are plans to have an alternative to FlexLayout that is actually a LayoutGroup and considers/affects direct children without FlexLayout components, but it hasn't been done yet ([#27](https://github.com/gilzoide/unity-flex-ui/issues/27)).

Hello! Sorry for the late response.

Yeah, I've set the Root to occupy all the horizontal space (as shown in the next gif, the Root is the red part).
But the problem is still that the TMP_Text doesn't stop expanding horizontally when the text overflows the Root width.
![Image](https://github.com/user-attachments/assets/c8c9faae-711b-4920-bc12-ef4e99c23a66)

I thought the problem here was that the CotentSizeFitter was overwriting the FlexLayout so I disabled it.
Then I saw that when a field of the FlexLayout is changed manually, the layout of the TMP_Text is refreshed and the text doesn't overflow the Root even if it's much wider.
I leave another gif to show what I'm trying to explain (english is not my first language, sorry).
![Image](https://github.com/user-attachments/assets/04cb5bac-9da8-480d-85ea-d4479760844b)

Now the question is: is there a way to manually refresh the FlexLayout from another monobehaviour? I saw that there are two public methods **RefreshRootLayout()** and **RefreshRootLayoutImmediate()**, but neither of them did anything.

I tested it with a simple component that implements ILayoutSelfController, which it calls SetLayoutHorizontal() when the text of the TMP_Text is changed.

```
    [ExecuteAlways]
    public class TMP_TextRectTracker : UIBehaviour, ILayoutSelfController
    {
        [SerializeField] private FlexLayout flexLayout;
        
        private RectTransform rectTransform;

        public RectTransform RectTransform
        {
            get
            {
                if (rectTransform == null)
                    rectTransform = GetComponent<RectTransform>();
                return rectTransform;
            }
        }
#if UNITY_EDITOR
        protected override void OnValidate()
        {
            SetDirty();
        }
#endif

        protected override void OnRectTransformDimensionsChange()
        {
            SetDirty();
        }

        protected override void OnEnable()
        {
            base.OnEnable();
            SetDirty();
        }

        protected override void OnDisable()
        {
            LayoutRebuilder.MarkLayoutForRebuild(rectTransform);
            base.OnDisable();
        }

        public void SetLayoutHorizontal()
        {
            Debug.Log("Set layout horizontal");
            if (flexLayout != null)
                flexLayout.RefreshRootLayout();
                // flexLayout.RefreshRootLayoutImmediate();
        }

        public void SetLayoutVertical()
        {
            Debug.Log("Set layout vertical");
        }

        protected void SetDirty()
        {
            if (!IsActive())
                return;

            LayoutRebuilder.MarkLayoutForRebuild(rectTransform);
        }
    }
```
